use_frameworks!

platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/guxingjian/SFPodSpec.git'

target 'SFPodB_Example' do
  pod 'SFPodB', :path => '../'

  target 'SFPodB_Tests' do
    inherit! :search_paths

    
  end
end
